// Mocks generated by Mockito 5.2.0 from annotations
// in easy_upi_payment/test/easy_upi_payment_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:easy_upi_payment/src/easy_upi_payment_platform_interface.dart'
    as _i2;
import 'package:easy_upi_payment/src/model/easy_upi_payment_model.dart' as _i5;
import 'package:easy_upi_payment/src/model/transaction_detail_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [EasyUpiPaymentPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockEasyUpiPaymentPlatform extends _i1.Mock
    implements _i2.EasyUpiPaymentPlatform {
  MockEasyUpiPaymentPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.TransactionDetailModel?> startPayment(
          _i5.EasyUpiPaymentModel? easyUpiPaymentModel) =>
      (super.noSuchMethod(
              Invocation.method(#startPayment, [easyUpiPaymentModel]),
              returnValue: Future<_i4.TransactionDetailModel?>.value())
          as _i3.Future<_i4.TransactionDetailModel?>);
}
