include: package:lint/analysis_options.yaml


analyzer:
  exclude:
    - "**.g.dart"

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    sort_pub_dependencies: false
